--cycle
--ansi
--multi
--border='rounded'
--color=border:#737994
--scrollbar='█'
--color=scrollbar:#838ba7
--prompt='❯ '
--color=prompt:#f4b8e4
--pointer='█'
--color=pointer:#ef9f76
--marker=' '
--color=marker:#a6d189
--color=gutter:#292c3c
--color=bg:#303446,fg:#b5bfe2
--color=bg+:#414559,fg+:#c6d0f5
--color=hl+:#ef9f76,hl:#ea999c
--color=header:#ca9ee6,info:#a6d189,spinner:#a6d189
--bind 'ctrl-p:preview-up'
--bind 'ctrl-n:preview-down'
--bind='ctrl-d:preview-page-down'
--bind='ctrl-u:preview-page-up'
--bind 'alt-p:toggle-preview'
--bind 'ctrl-y:execute-silent(printf {} | fish_clipboard_copy)+abort'
--bind 'ctrl-o:become($EDITOR {} &>/dev/tty)'
