# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  timeFormat: Jan 2 06
  theme:
    activeBorderColor:
      - "#ca9ee6"
      - bold
    inactiveBorderColor:
      - "#a5adce"
    optionsTextColor:
      - "#8caaee"
    selectedLineBgColor:
      - "#414559"
    cherryPickedCommitBgColor:
      - "#51576d"
    cherryPickedCommitFgColor:
      - "#ca9ee6"
    unstagedChangesColor:
      - "#e78284"
    defaultFgColor:
      - "#c6d0f5"
    searchingActiveBorderColor:
      - "#e5c890"
  authorColors:
    "winnie": "#f4b8e4"
    "dependabot[bot]": "#8caaee"
    "*": "#babbf1"
  nerdFontsVersion: "3"
git:
  pagers:
    - pager: 'delta --paging=never --features=catppuccin-frappe --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"'
    - externalDiffCommand: difft --color=always
  parseEmoji: true
  overrideGpg: true
os:
  editPreset: "nvim-remote"
keybinding:
  universal:
    createPatchOptionsMenu: <c-x>
    scrollUpMain-alt1: <c-p>
    scrollDownMain-alt1: <c-n>
    gotoTop-alt: g
    gotoBottom-alt: G
customCommands:
  - key: "C"
    command: "meteor"
    description: "Commit with meteor"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
  - key: "t"
    context: "files"
    description: "Interactive conventional commit"
    prompts:
      - type: "menu"
        title: "Type of change"
        key: "Type"
        options:
          - name: "✨ feat"
            value: "feat"
            key: "f"
          - name: "🐛 fix"
            value: "fix"
            key: "x"
          - name: "📚 docs"
            value: "docs"
            key: "d"
          - name: "🎨 style"
            value: "style"
            key: "s"
          - name: "♻️ refactor"
            value: "refactor"
            key: "r"
          - name: "⚡ perf"
            value: "perf"
            key: "p"
          - name: "🧪 test"
            value: "test"
            key: "t"
          - name: "🛠️ build"
            value: "build"
            key: "b"
          - name: "🚧 ci"
            value: "ci"
            key: "i"
          - name: "🧰 chore"
            value: "chore"
            key: "c"
          - name: "📼 revert"
            value: "revert"
            key: "z"
          - name: "🤖 agent"
            value: "agent"
            key: "a"
      - type: "input"
        title: "Scope (optional):"
        key: "Scope"
        initialValue: ""
      - type: "menu"
        title: "Breaking change?"
        key: "Breaking"
        options:
          - name: "no"
            value: "no"
            key: "n"
          - name: "yes"
            value: "yes"
            key: "y"
      - type: "menu"
        title: "Use emojis in message?"
        key: "Emoji"
        options:
          - name: "no"
            value: "no"
            key: "n"
          - name: "yes"
            value: "yes"
            key: "y"
      - type: "input"
        title: "Message:"
        key: "Message"
        initialValue: ""
      - type: "confirm"
        title: "Commit this?"
        key: "Confirm"
        body: |
          {{.Form.Type}}{{ if .Form.Scope }}({{.Form.Scope}}){{ end }}{{ if eq .Form.Breaking "yes" }}!{{ end }}: {{ if eq .Form.Emoji "yes"}}{{ if eq .Form.Type "feat" }}✨{{ else if eq .Form.Type "fix" }}🐛{{ else if eq .Form.Type "docs" }}📚{{ else if eq .Form.Type "style" }}🎨{{ else if eq .Form.Type "refactor" }}♻️{{ else if eq .Form.Type "perf" }}⚡{{ else if eq .Form.Type "test" }}🧪{{ else if eq .Form.Type "build" }}🛠️{{ else if eq .Form.Type "ci" }}🚧{{ else if eq .Form.Type "chore" }}🧰{{ else if eq .Form.Type "revert" }}📼{{else if eq .Form.Type "agent"}}🤖{{ end }} {{ end }}{{.Form.Message}}
    command: >-
      git commit --message '{{.Form.Type}}{{ if .Form.Scope }}({{.Form.Scope}}){{ end }}{{ if eq .Form.Breaking "yes" }}!{{ end }}: {{ if eq .Form.Emoji "yes"}}{{ if eq .Form.Type "feat" }}✨{{ else if eq .Form.Type "fix" }}🐛{{ else if eq .Form.Type "docs" }}📚{{ else if eq .Form.Type "style" }}🎨{{ else if eq .Form.Type "refactor" }}♻️{{ else if eq .Form.Type "perf" }}⚡{{ else if eq .Form.Type "test" }}🧪{{ else if eq .Form.Type "build" }}🛠️{{ else if eq .Form.Type "ci" }}🚧{{ else if eq .Form.Type "chore" }}🧰{{ else if eq .Form.Type "revert" }}📼{{else if eq .Form.Type "agent"}}🤖{{ end }} {{ end }}{{.Form.Message}}'
    loadingText: Committing conventionally...
