function confcomp -d "Compile modular fish config into a single file for faster startup"
    argparse h/help -- $argv
    or return

    if set -q _flag_help
        echo "Compile modular user_conf/*.fish files into a single config file."
        echo "Eliminates the glob+source loop overhead at shell startup."
        echo ""
        echo "Reads files from \$__fish_config_dir/user_conf/ and writes"
        echo "a concatenated config to \$__fish_config_dir/config_compiled.fish"
        echo ""
        echo "Namespace conventions:"
        echo "  0* — core env, PATH, system tooling (always loaded)"
        echo "  1* — language setup (always loaded)"
        echo "  2* — interactive tooling (guarded by is-interactive)"
        logirl help_usage "fish_compile [OPTIONS]"
        logirl help_header Options
        logirl help_flag h/help "Show this help"
        # TODO: add a --refresh flag that re-captures output from tools
        #       that generate shell init code (brew shellenv, starship init,
        #       zoxide init, vivid generate, etc.) and inlines the fresh
        #       output into the compiled file. Useful after tool upgrades.
        return 0
    end

    set -l conf_dir $__fish_config_dir/user_conf
    set -l out $__fish_config_dir/config_compiled.fish

    if not test -d "$conf_dir"
        logirl error "user_conf directory not found: $conf_dir"
        return 1
    end

    # Collect files by namespace
    set -l core_files $conf_dir/0*.fish
    set -l lang_files $conf_dir/1*.fish
    set -l interactive_files $conf_dir/2*.fish

    if test (count $core_files $lang_files $interactive_files) -eq 0
        logirl error "No .fish files found in $conf_dir"
        return 1
    end

    logirl info "Compiling config from $conf_dir"

    # Write header
    printf '# AUTO-GENERATED by fish_compile — do not edit directly\n' >$out
    printf '# Source files: %s/user_conf/*.fish\n' $__fish_config_dir >>$out
    printf '# Regenerate with: fish_compile\n' >>$out
    printf '# Generated: %s\n\n' (date -Iseconds) >>$out

    # 0* — core env (always loaded)
    for file in $core_files
        printf '\n# --- %s ---\n' (basename $file) >>$out
        cat $file >>$out
        printf '\n' >>$out
    end

    # 1* — language setup (always loaded)
    for file in $lang_files
        printf '\n# --- %s ---\n' (basename $file) >>$out
        cat $file >>$out
        printf '\n' >>$out
    end

    # 2* — interactive (guarded)
    printf '\nif status is-interactive\n' >>$out
    for file in $interactive_files
        printf '\n# --- %s ---\n' (basename $file) >>$out
        cat $file >>$out
        printf '\n' >>$out
    end
    printf '\nend # status is-interactive\n' >>$out

    set -l file_count (count $core_files $lang_files $interactive_files)
    set -l line_count (count < $out)
    logirl success "Compiled $file_count files → $out ($line_count lines)"

    # TODO: implement this function end-to-end if maintaining
    #       the single-file config_refactor.fish becomes tedious.
    #       Current approach: config_refactor.fish is hand-maintained
    #       with inlined tool outputs. This function provides the
    #       scaffolding to automate that if needed.
end
