local M = {}

-- Paste URL over visual selection to create markdown link
-- Mimics GitHub's behavior of converting selected text + pasted URL into [text](url)
function M.paste_as_markdown_link()
  -- Get visual selection marks (already set when exiting visual mode)
  local start_pos = vim.fn.getpos("'<")
  local end_pos = vim.fn.getpos("'>")

  local start_row = start_pos[2] - 1 -- Convert to 0-indexed
  local start_col = start_pos[3] - 1
  local end_row = end_pos[2] - 1
  -- For visual selection, '> points to last char (inclusive), so add 1 for exclusive end
  local end_col = end_pos[3]

  -- Get the selected text directly from buffer
  local lines = vim.api.nvim_buf_get_text(0, start_row, start_col, end_row, end_col, {})
  local selected_text = table.concat(lines, "\n")

  -- Get URL from system clipboard
  local url = vim.fn.getreg("+")

  -- Trim whitespace from both
  selected_text = selected_text:gsub("^%s+", ""):gsub("%s+$", "")
  url = url:gsub("^%s+", ""):gsub("%s+$", "")

  -- Validate we have both text and URL
  if selected_text == "" or url == "" then
    vim.notify("Need selected text and URL in clipboard", vim.log.levels.WARN)
    return
  end

  -- Create markdown link
  local markdown_link = string.format("[%s](%s)", selected_text, url)

  -- Replace the selection in buffer
  vim.api.nvim_buf_set_text(0, start_row, start_col, end_row, end_col, { markdown_link })
end

-- Fix over-compact pipe spacing in 'compact' style Markdown tables
-- this is primarily for fixing tables generated by Claude Code and other agents
function M.markdown_table_fix_compact_spacing(opts)
  local r = opts.line1 .. "," .. opts.line2
  -- Normalize spacing around all pipes to exactly one space on each side
  vim.cmd("silent! " .. r .. [[s/\s*|\s*/ | /ge]])

  -- Remove the leading space before the first pipe
  vim.cmd("silent! " .. r .. [[s/^ |/|/e]])

  -- Remove the trailing space after the last pipe
  vim.cmd("silent! " .. r .. [[s/| $/|/e]])

  -- Clear search highlighting
  vim.cmd("nohlsearch")
end

function M.setup()
  -- Create the command for markdown files
  vim.api.nvim_create_autocmd("FileType", {
    pattern = "markdown",
    callback = function()
      -- Create a buffer-local command
      vim.api.nvim_buf_create_user_command(0, "MarkdownPasteLink", function()
        M.paste_as_markdown_link()
      end, {
        range = true,
        desc = "Paste URL as markdown link over selection",
      })

      vim.api.nvim_buf_create_user_command(0, "MarkdownTableFixCompactPipeSpacing", function(opts)
        M.markdown_table_fix_compact_spacing(opts)
      end, {
        range = true,
        desc = "Fix Markdown table pipe spacing for compact format",
      })
    end,
  })
end

return M
